# Generated by Django 5.0.7 on 2024-07-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('muscle', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=300)),
            ],
        ),
    ]
