# Generated by Django 5.0.7 on 2024-07-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(max_length=500),
        ),
    ]
