# Generated by Django 5.0.7 on 2024-07-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0002_alter_exercise_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(choices=[('abdominals', 'Abdominals'), ('biceps', 'Biceps'), ('calves', 'Calves'), ('Chest', 'Chest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility')], max_length=50),
        ),
    ]
