# Generated by Django 5.0.7 on 2024-07-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0003_alter_exercise_equipment_alter_exercise_muscle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'Barbell'), ('body', 'Body'), ('dumbbells', 'Dumbbells'), ('kettlebells', 'Kettlebells'), ('resistance_band', 'Resistance_band')], max_length=50),
        ),
    ]
