# Generated by Django 5.0.7 on 2024-07-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0004_alter_exercise_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('calisthenic', 'Calisthenic'), ('strength', 'Strength'), ('flexibility', 'Flexibility')], max_length=50),
        ),
    ]
