# Generated by Django 5.0.7 on 2024-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0005_alter_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'barbell'), ('body', 'body'), ('dumbbells', 'dumbbells'), ('kettlebells', 'kettlebells'), ('machine', 'machine'), ('other', 'other'), ('resistance_band', 'resistance_band')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(choices=[('abdominals', 'abdominals'), ('biceps', 'biceps'), ('calves', 'calves'), ('chest', 'chest'), ('forearms', 'forearms'), ('hamstrings', 'hamstrings'), ('middle_back', 'middle_back'), ('lats', 'lats'), ('quads', 'quads'), ('shoulders', 'shoulders'), ('triceps', 'triceps'), ('traps', 'traps')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('cardio', 'cardio'), ('calisthenic', 'calisthenic'), ('strength', 'strength'), ('flexibility', 'flexibility')], max_length=50),
        ),
    ]
