# Generated by Django 5.0.7 on 2024-07-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0006_alter_exercise_equipment_alter_exercise_muscle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('calisthenic', 'Calisthenic'), ('strength', 'Strength'), ('flexibililty', 'Flexibility')], max_length=50),
        ),
    ]
