# Generated by Django 5.0.7 on 2024-07-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0007_alter_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'Barbell'), ('body', 'Body'), ('dumbbells', 'Dumbbells'), ('machine', 'Machine'), ('other', 'Other'), ('resistance_band', 'Resistance Band')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(choices=[('abdominals', 'Abdominals'), ('biceps', 'Biceps'), ('calves', 'Calves'), ('chest', 'Chest'), ('forearms', 'Forearms'), ('hamstrings', 'Hamstrings'), ('middle_back', 'Middle Back'), ('lats', 'Lats'), ('quads', 'Quads'), ('shoulders', 'Shoulders'), ('triceps', 'Triceps'), ('traps', 'Traps')], max_length=50),
        ),
    ]
