# Generated by Django 5.0.7 on 2024-07-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0008_alter_exercise_equipment_alter_exercise_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibililty', 'Flexibility')], max_length=50),
        ),
    ]
