# Generated by Django 5.0.7 on 2024-07-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0009_alter_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(choices=[('abdominals', 'Abdominals'), ('biceps', 'Biceps'), ('calves', 'Calves'), ('cardio', 'Cardio'), ('chest', 'Chest'), ('forearms', 'Forearms'), ('hamstrings', 'Hamstrings'), ('middle_back', 'Middle Back'), ('lats', 'Lats'), ('quads', 'Quads'), ('shoulders', 'Shoulders'), ('triceps', 'Triceps'), ('traps', 'Traps')], max_length=50),
        ),
    ]
