# Generated by Django 5.0.7 on 2024-07-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseapi', '0010_alter_exercise_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'Barbell'), ('body', 'Body'), ('dumbbells', 'Dumbbells'), ('machine', 'Machine'), ('other', 'Other'), ('resistance_band', 'Resistance Band'), ('treadmill', 'Treadmill')], max_length=50),
        ),
    ]
